# Generated by Django 4.1.7 on 2023-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=20)),
            ],
        ),
    ]
